rentit-frontend:
    image: akaiz/rentit:1
    ports:
      - "8000:8000"
    links:
      - rentit
rentit:
  image: akaiz/rentitservice:1
  ports:
    - "8090:8090"
  links:
    - postgres
  environment:
    POSTGRES: postgres
    POSTGRES_USERNAME: postgres
    POSTGRES_PASSWORD: mysecretword

postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: mysecretword
